services:
  server:
    build: ./server
    ports:
      - "8000:8000"
  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - server
