# Generated by Django 5.0.4 on 2024-05-05 13:05

import library.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=library.utils.generate_filename),
        ),
    ]
