# Generated by Django 5.0.4 on 2024-05-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_profile_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('assistant', 'Assistant'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
